import type { BankPreset } from './banks'

type Entry = BankPreset & { featured?: boolean; rank: number }

/** Catálogo amplo (BR + internacional). `featured` aparece sem busca; `rank` ordena (menor = mais conhecido). */
export const BANK_CATALOG: Entry[] = [
  // ── Destaques Brasil ─────────────────────────────────────────────────────
  { id: 'nubank', name: 'Nubank', color: '#820AD1', mark: 'nu', rank: 1, featured: true, domain: 'nubank.com.br', keywords: ['roxinho', 'nu'] },
  { id: 'itau', name: 'Itaú', color: '#EC7000', mark: 'Itaú', rank: 2, featured: true, domain: 'itau.com.br', keywords: ['itaú unibanco', 'itaucard'] },
  { id: 'bradesco', name: 'Bradesco', color: '#CC092F', mark: 'B', rank: 3, featured: true, domain: 'bradesco.com.br', keywords: ['bradesco fin'] },
  { id: 'santander', name: 'Santander', color: '#EC0000', mark: 'S', rank: 4, featured: true, domain: 'santander.com.br', keywords: ['santander brasil'] },
  { id: 'bb', name: 'Banco do Brasil', color: '#FDF429', mark: 'BB', rank: 5, featured: true, domain: 'bb.com.br', keywords: ['bb', 'banco brasil'] },
  { id: 'caixa', name: 'Caixa', color: '#005CA9', mark: 'CX', rank: 6, featured: true, domain: 'caixa.gov.br', keywords: ['cef', 'caixa econômica'] },
  { id: 'inter', name: 'Inter', color: '#FF7A00', mark: 'inter', rank: 7, featured: true, domain: 'bancointer.com.br', keywords: ['banco inter'] },
  { id: 'c6', name: 'C6 Bank', color: '#242424', mark: 'C6', rank: 8, featured: true, domain: 'c6bank.com.br', keywords: ['c6 bank'] },
  { id: 'picpay', name: 'PicPay', color: '#21C25E', mark: 'P', rank: 9, featured: true, domain: 'picpay.com', keywords: [] },
  { id: 'mercadopago', name: 'Mercado Pago', color: '#009EE3', mark: 'MP', rank: 10, featured: true, domain: 'mercadopago.com.br', keywords: ['mercado pago', 'mp'] },
  { id: 'neon', name: 'Neon', color: '#00D4FF', mark: 'neon', rank: 11, featured: true, domain: 'neon.com.br', keywords: [] },
  { id: 'pagbank', name: 'PagBank', color: '#00A868', mark: 'PB', rank: 12, featured: true, domain: 'pagbank.com.br', keywords: ['pagseguro', 'pag bank'] },
  { id: 'sicoob', name: 'Sicoob', color: '#009639', mark: 'Sc', rank: 13, featured: true, domain: 'sicoob.com.br', keywords: ['cooperativa sicoob'] },
  { id: 'sicredi', name: 'Sicredi', color: '#3E6C45', mark: 'Si', rank: 14, featured: true, domain: 'sicredi.com.br', keywords: ['cooperativa sicredi'] },
  { id: 'banrisul', name: 'Banrisul', color: '#005BAA', mark: 'BR', rank: 15, featured: true, domain: 'banrisul.com.br', keywords: [] },
  { id: 'pan', name: 'Banco Pan', color: '#0066CC', mark: 'Pan', rank: 16, featured: true, domain: 'bancopan.com.br', keywords: ['pan'] },
  { id: 'amex', name: 'American Express', color: '#006FCF', mark: 'AmEx', rank: 20, domain: 'americanexpress.com', keywords: ['american express', 'american', 'amex', 'express'] },
  { id: 'mercantil', name: 'Mercantil', color: '#003641', mark: 'M', rank: 21, domain: 'mercantil.com.br', keywords: ['banco mercantil', 'mercantil do brasil'] },
  { id: 'btg', name: 'BTG Pactual', color: '#002855', mark: 'BTG', rank: 22, domain: 'btgpactual.com', keywords: ['btg', 'pactual'] },
  { id: 'xp', name: 'XP', color: '#111111', mark: 'XP', rank: 23, domain: 'xpinc.com', keywords: ['xp investimentos'] },
  { id: 'safra', name: 'Safra', color: '#1B365D', mark: 'Safra', rank: 24, domain: 'safra.com.br', keywords: [] },
  { id: 'original', name: 'Original', color: '#00A651', mark: 'O', rank: 25, domain: 'original.com.br', keywords: ['banco original'] },

  // ── Brasil (demais) ──────────────────────────────────────────────────────
  { id: 'bv', name: 'BV', color: '#004B8D', mark: 'BV', rank: 30, domain: 'bv.com.br', keywords: ['banco bv', 'votorantim'] },
  { id: 'daycoval', name: 'Daycoval', color: '#003DA5', mark: 'D', rank: 31, domain: 'daycoval.com.br', keywords: [] },
  { id: 'rico', name: 'Rico', color: '#FF6600', mark: 'R', rank: 32, domain: 'rico.com.vc', keywords: ['rico investimentos'] },
  { id: 'clear', name: 'Clear', color: '#000000', mark: 'Cl', rank: 33, domain: 'clear.com.br', keywords: ['clear corretora'] },
  { id: 'next', name: 'Next', color: '#00C853', mark: 'Nx', rank: 34, domain: 'next.me', keywords: ['next bradesco'] },
  { id: 'digio', name: 'Digio', color: '#0066FF', mark: 'Dg', rank: 35, domain: 'digio.com.br', keywords: [] },
  { id: 'agibank', name: 'Agibank', color: '#87CE00', mark: 'Ag', rank: 36, domain: 'agibank.com.br', keywords: [] },
  { id: 'bmg', name: 'BMG', color: '#FF6600', mark: 'BMG', rank: 37, domain: 'bancobmg.com.br', keywords: [] },
  { id: 'credicard', name: 'Credicard', color: '#E4002B', mark: 'CC', rank: 38, domain: 'credicard.com.br', keywords: [] },
  { id: 'portoseguro', name: 'Porto Seguro', color: '#0066CC', mark: 'PS', rank: 39, domain: 'portoseguro.com.br', keywords: ['porto bank'] },
  { id: 'bs2', name: 'BS2', color: '#003366', mark: 'BS2', rank: 40, domain: 'bs2.com.br', keywords: [] },
  { id: 'toro', name: 'Toro Investimentos', color: '#6366F1', mark: 'T', rank: 41, domain: 'toroinvestimentos.com.br', keywords: ['toro'] },
  { id: 'genial', name: 'Genial', color: '#0F172A', mark: 'G', rank: 42, domain: 'genialinvestimentos.com.br', keywords: ['genial investimentos'] },
  { id: 'sofisa', name: 'Sofisa', color: '#00A859', mark: 'Sf', rank: 43, domain: 'sofisadireto.com.br', keywords: ['sofisa direto'] },
  { id: 'will', name: 'Will Bank', color: '#FFD100', mark: 'W', rank: 44, domain: 'willbank.com.br', keywords: ['will'] },
  { id: 'stone', name: 'Stone', color: '#00A868', mark: 'St', rank: 45, domain: 'stone.com.br', keywords: ['stone pagamentos'] },
  { id: 'crefisa', name: 'Crefisa', color: '#FFD200', mark: 'Cr', rank: 46, domain: 'crefisa.com.br', keywords: [] },
  { id: 'creditas', name: 'Creditas', color: '#00B8A9', mark: 'Cr', rank: 47, domain: 'creditas.com', keywords: [] },
  { id: 'banestes', name: 'Banestes', color: '#0054A6', mark: 'BE', rank: 48, domain: 'banestes.com.br', keywords: ['banco do estado espírito santo'] },
  { id: 'brb', name: 'BRB', color: '#005EB8', mark: 'BRB', rank: 49, domain: 'brb.com.br', keywords: ['banco de brasília'] },
  { id: 'banpara', name: 'Banpará', color: '#005A2B', mark: 'Bp', rank: 50, domain: 'banpara.b.br', keywords: ['banco da amazonia', 'basa'] },
  { id: 'banese', name: 'Banese', color: '#006B3F', mark: 'Bs', rank: 51, domain: 'banese.com.br', keywords: [] },
  { id: 'abc', name: 'ABC Brasil', color: '#FFB81C', mark: 'ABC', rank: 52, domain: 'abcbrasil.com.br', keywords: [] },
  { id: 'alfa', name: 'Alfa', color: '#003DA5', mark: 'Al', rank: 53, domain: 'bancoalfa.com.br', keywords: ['banco alfa'] },
  { id: 'arbi', name: 'Arbi', color: '#1E3A8A', mark: 'Ar', rank: 54, domain: 'bancarbi.com.br', keywords: [] },
  { id: 'bocom', name: 'Bocom BBM', color: '#C8102E', mark: 'BBM', rank: 55, domain: 'bocombbm.com.br', keywords: ['bbm'] },
  { id: 'citibank-br', name: 'Citibank', color: '#003B70', mark: 'Ci', rank: 56, domain: 'citibank.com.br', keywords: ['citi brasil'] },
  { id: 'fibra', name: 'Fibra', color: '#7C3AED', mark: 'Fb', rank: 57, domain: 'bancofibra.com.br', keywords: [] },
  { id: 'indusval', name: 'Indusval', color: '#002855', mark: 'Iv', rank: 58, domain: 'bi.com.br', keywords: ['bi indusval'] },
  { id: 'jpmorgan-br', name: 'J.P. Morgan', color: '#006BA6', mark: 'JPM', rank: 59, domain: 'jpmorgan.com', keywords: ['jp morgan'] },
  { id: 'letsbank', name: 'Letsbank', color: '#FF6B00', mark: 'Lb', rank: 60, domain: 'letsbank.com.br', keywords: [] },
  { id: 'modal', name: 'Modal', color: '#111827', mark: 'Md', rank: 61, domain: 'modal.com.br', keywords: ['modalmais'] },
  { id: 'ourinvest', name: 'Ourinvest', color: '#0F766E', mark: 'Oi', rank: 62, domain: 'ourinvest.com.br', keywords: [] },
  { id: 'parana', name: 'Paraná Banco', color: '#006341', mark: 'Pr', rank: 63, domain: 'paranabanco.com.br', keywords: [] },
  { id: 'pine', name: 'Pine', color: '#166534', mark: 'Pi', rank: 64, domain: 'pine.com', keywords: ['banco pine'] },
  { id: 'rabobank-br', name: 'Rabobank', color: '#FF6600', mark: 'Rb', rank: 65, domain: 'rabobank.com.br', keywords: [] },
  { id: 'rendimento', name: 'Rendimento', color: '#004B87', mark: 'Re', rank: 66, domain: 'bancorendimento.com.br', keywords: [] },
  { id: 'semear', name: 'Semear', color: '#059669', mark: 'Se', rank: 67, domain: 'semear.com.br', keywords: [] },
  { id: 'topazio', name: 'Topázio', color: '#0284C7', mark: 'Tz', rank: 68, domain: 'bancotopazio.com.br', keywords: [] },
  { id: 'unicred', name: 'Unicred', color: '#006747', mark: 'Uc', rank: 69, domain: 'unicred.com.br', keywords: [] },
  { id: 'woop', name: 'Woop', color: '#7C3AED', mark: 'Wo', rank: 70, domain: 'woop.com.br', keywords: ['sicredi woop'] },
  { id: 'superdigital', name: 'Superdigital', color: '#7C3AED', mark: 'Sd', rank: 71, domain: 'superdigital.com.br', keywords: [] },
  { id: 'bancointerpj', name: 'Inter Empresas', color: '#FF7A00', mark: 'Ie', rank: 72, domain: 'bancointer.com.br', keywords: ['inter pj'] },

  // ── Cartões / bandeiras / benefícios ─────────────────────────────────────
  { id: 'elo', name: 'Elo', color: '#FFCB05', mark: 'elo', rank: 80, domain: 'elo.com.br', keywords: ['cartão elo'] },
  { id: 'visa', name: 'Visa', color: '#1A1F71', mark: 'V', rank: 81, domain: 'visa.com.br', keywords: ['cartão visa'] },
  { id: 'mastercard', name: 'Mastercard', color: '#EB001B', mark: 'MC', rank: 82, domain: 'mastercard.com.br', keywords: ['cartão master'] },
  { id: 'hipercard', name: 'Hipercard', color: '#B91C1C', mark: 'Hp', rank: 83, domain: 'hipercard.com.br', keywords: [] },
  { id: 'diners', name: 'Diners Club', color: '#0079BE', mark: 'DC', rank: 84, domain: 'dinersclub.com', keywords: ['diners'] },
  { id: 'alelo', name: 'Alelo', color: '#00843D', mark: 'Al', rank: 85, domain: 'alelo.com.br', keywords: ['vale alimentação'] },
  { id: 'vr', name: 'VR', color: '#00A651', mark: 'VR', rank: 86, domain: 'vr.com.br', keywords: ['vale refeição'] },
  { id: 'ticket', name: 'Ticket', color: '#E4002B', mark: 'Tk', rank: 87, domain: 'ticket.com.br', keywords: ['edenred'] },
  { id: 'sodexo', name: 'Pluxee (Sodexo)', color: '#E30613', mark: 'Pl', rank: 88, domain: 'pluxee.com.br', keywords: ['sodexo'] },

  // ── Fintechs / global digital ────────────────────────────────────────────
  { id: 'avenue', name: 'Avenue', color: '#0EA5E9', mark: 'Av', rank: 100, domain: 'avenue.us', keywords: [] },
  { id: 'nomad', name: 'Nomad', color: '#1A1A1A', mark: 'N', rank: 101, domain: 'nomadglobal.com', keywords: [] },
  { id: 'wise', name: 'Wise', color: '#9FE870', mark: 'W', rank: 102, domain: 'wise.com', keywords: ['transferwise'] },
  { id: 'revolut', name: 'Revolut', color: '#191C1F', mark: 'Rv', rank: 103, domain: 'revolut.com', keywords: [] },
  { id: 'n26', name: 'N26', color: '#36A18B', mark: 'N26', rank: 104, domain: 'n26.com', keywords: [] },
  { id: 'monzo', name: 'Monzo', color: '#FF4B44', mark: 'Mz', rank: 105, domain: 'monzo.com', keywords: [] },
  { id: 'starling', name: 'Starling', color: '#6935D3', mark: 'St', rank: 106, domain: 'starlingbank.com', keywords: [] },
  { id: 'paypal', name: 'PayPal', color: '#003087', mark: 'PP', rank: 107, domain: 'paypal.com', keywords: [] },
  { id: 'binance', name: 'Binance', color: '#F0B90B', mark: 'B', rank: 108, domain: 'binance.com', keywords: [] },
  { id: 'mercadolibre', name: 'Mercado Libre', color: '#FFE600', mark: 'ML', rank: 109, domain: 'mercadolibre.com', keywords: ['mercado livre conta'] },

  // ── EUA / Canadá ─────────────────────────────────────────────────────────
  { id: 'chase', name: 'Chase', color: '#117ACA', mark: 'Ch', rank: 120, domain: 'chase.com', keywords: ['jp morgan chase'] },
  { id: 'bofa', name: 'Bank of America', color: '#E31837', mark: 'BoA', rank: 121, domain: 'bankofamerica.com', keywords: ['bofa'] },
  { id: 'wellsfargo', name: 'Wells Fargo', color: '#D71E28', mark: 'WF', rank: 122, domain: 'wellsfargo.com', keywords: [] },
  { id: 'citi', name: 'Citibank', color: '#003B70', mark: 'Ci', rank: 123, domain: 'citi.com', keywords: ['citigroup'] },
  { id: 'capitalone', name: 'Capital One', color: '#004977', mark: 'C1', rank: 124, domain: 'capitalone.com', keywords: [] },
  { id: 'discover', name: 'Discover', color: '#FF6000', mark: 'Ds', rank: 125, domain: 'discover.com', keywords: [] },
  { id: 'usbank', name: 'U.S. Bank', color: '#0C2074', mark: 'US', rank: 126, domain: 'usbank.com', keywords: [] },
  { id: 'pnc', name: 'PNC', color: '#F58025', mark: 'PNC', rank: 127, domain: 'pnc.com', keywords: [] },
  { id: 'tdbank', name: 'TD Bank', color: '#34A853', mark: 'TD', rank: 128, domain: 'td.com', keywords: ['toronto dominion'] },
  { id: 'schwab', name: 'Charles Schwab', color: '#00A0DF', mark: 'Sc', rank: 129, domain: 'schwab.com', keywords: [] },
  { id: 'fidelity', name: 'Fidelity', color: '#4AA84B', mark: 'Fi', rank: 130, domain: 'fidelity.com', keywords: [] },
  { id: 'goldman', name: 'Goldman Sachs', color: '#6F9FD8', mark: 'GS', rank: 131, domain: 'goldmansachs.com', keywords: ['marcus'] },
  { id: 'morganstanley', name: 'Morgan Stanley', color: '#004080', mark: 'MS', rank: 132, domain: 'morganstanley.com', keywords: [] },
  { id: 'truist', name: 'Truist', color: '#8031A7', mark: 'Tr', rank: 133, domain: 'truist.com', keywords: [] },
  { id: 'ally', name: 'Ally Bank', color: '#650360', mark: 'Al', rank: 134, domain: 'ally.com', keywords: [] },
  { id: 'sofi', name: 'SoFi', color: '#00A2C7', mark: 'Sf', rank: 135, domain: 'sofi.com', keywords: [] },

  // ── Europa / UK / LATAM ──────────────────────────────────────────────────
  { id: 'hsbc', name: 'HSBC', color: '#DB0011', mark: 'HS', rank: 140, domain: 'hsbc.com', keywords: [] },
  { id: 'barclays', name: 'Barclays', color: '#00AEEF', mark: 'Ba', rank: 141, domain: 'barclays.com', keywords: [] },
  { id: 'lloyds', name: 'Lloyds', color: '#006A4D', mark: 'Ll', rank: 142, domain: 'lloydsbank.com', keywords: [] },
  { id: 'natwest', name: 'NatWest', color: '#42145F', mark: 'NW', rank: 143, domain: 'natwest.com', keywords: [] },
  { id: 'santander-uk', name: 'Santander UK', color: '#EC0000', mark: 'S', rank: 144, domain: 'santander.co.uk', keywords: [] },
  { id: 'deutsche', name: 'Deutsche Bank', color: '#0018A8', mark: 'DB', rank: 145, domain: 'db.com', keywords: [] },
  { id: 'bnpp', name: 'BNP Paribas', color: '#00915A', mark: 'BNP', rank: 146, domain: 'bnpparibas.com', keywords: [] },
  { id: 'ing', name: 'ING', color: '#FF6200', mark: 'IN', rank: 147, domain: 'ing.com', keywords: [] },
  { id: 'bbva', name: 'BBVA', color: '#004481', mark: 'BB', rank: 148, domain: 'bbva.com', keywords: [] },
  { id: 'santander-es', name: 'Santander España', color: '#EC0000', mark: 'S', rank: 149, domain: 'bancosantander.es', keywords: [] },
  { id: 'itau-chile', name: 'Itaú Chile', color: '#EC7000', mark: 'It', rank: 150, domain: 'itau.cl', keywords: [] },
  { id: 'bradesco-arg', name: 'Bradesco Argentina', color: '#CC092F', mark: 'B', rank: 151, domain: 'bradesco.com.ar', keywords: [] },
  { id: 'galicia', name: 'Galicia', color: '#FF6600', mark: 'Ga', rank: 152, domain: 'bancogalicia.com', keywords: ['banco galicia'] },
  { id: 'macro', name: 'Macro', color: '#003DA5', mark: 'Ma', rank: 153, domain: 'macro.com.ar', keywords: ['banco macro'] },
  { id: 'santander-mx', name: 'Santander México', color: '#EC0000', mark: 'S', rank: 154, domain: 'santander.com.mx', keywords: [] },
  { id: 'bbva-mx', name: 'BBVA México', color: '#004481', mark: 'BB', rank: 155, domain: 'bbva.mx', keywords: [] },
  { id: 'interbank', name: 'Interbank', color: '#00A651', mark: 'Ib', rank: 156, domain: 'interbank.pe', keywords: ['peru'] },
  { id: 'bcp', name: 'BCP', color: '#FF6600', mark: 'BCP', rank: 157, domain: 'viabcp.com', keywords: ['peru crédito'] },
  { id: 'davivienda', name: 'Davivienda', color: '#E30613', mark: 'Dv', rank: 158, domain: 'davivienda.com', keywords: ['colombia'] },
  { id: 'bancolombia', name: 'Bancolombia', color: '#FFD200', mark: 'Bc', rank: 159, domain: 'bancolombia.com', keywords: [] },
  { id: 'mercantil-ve', name: 'Mercantil Venezuela', color: '#003641', mark: 'M', rank: 160, domain: 'mercantilbanco.com', keywords: [] },

  // ── Ásia / Oceania / África ──────────────────────────────────────────────
  { id: 'icbc', name: 'ICBC', color: '#C8102E', mark: 'IC', rank: 170, domain: 'icbc.com.cn', keywords: ['china'] },
  { id: 'ccb', name: 'China Construction Bank', color: '#003DA5', mark: 'CCB', rank: 171, domain: 'ccb.com', keywords: ['ccb'] },
  { id: 'mufg', name: 'MUFG', color: '#D71920', mark: 'MU', rank: 172, domain: 'mufg.jp', keywords: ['tokyo mitsubishi'] },
  { id: 'mizuho', name: 'Mizuho', color: '#003DA5', mark: 'Mz', rank: 173, domain: 'mizuhogroup.com', keywords: [] },
  { id: 'dbs', name: 'DBS', color: '#FF3333', mark: 'DB', rank: 174, domain: 'dbs.com', keywords: ['singapura'] },
  { id: 'ocbc', name: 'OCBC', color: '#ED1C24', mark: 'OC', rank: 175, domain: 'ocbc.com', keywords: [] },
  { id: 'hdfc', name: 'HDFC Bank', color: '#004B8D', mark: 'Hd', rank: 176, domain: 'hdfcbank.com', keywords: ['india'] },
  { id: 'sbi', name: 'State Bank of India', color: '#22409A', mark: 'SBI', rank: 177, domain: 'sbi.co.in', keywords: ['sbi india'] },
  { id: 'commbank', name: 'CommBank', color: '#FFCC00', mark: 'Cb', rank: 178, domain: 'commbank.com.au', keywords: ['commonwealth australia'] },
  { id: 'anz', name: 'ANZ', color: '#007DBA', mark: 'AN', rank: 179, domain: 'anz.com', keywords: [] },
  { id: 'standard-chartered', name: 'Standard Chartered', color: '#0473EA', mark: 'SC', rank: 180, domain: 'sc.com', keywords: [] },
  { id: 'firstrand', name: 'FirstRand', color: '#00A651', mark: 'FR', rank: 181, domain: 'firstrand.co.za', keywords: ['fnb south africa'] },

  // ── Investimentos / corretoras ───────────────────────────────────────────
  { id: 'interactive-brokers', name: 'Interactive Brokers', color: '#D71920', mark: 'IB', rank: 190, domain: 'interactivebrokers.com', keywords: ['ibkr'] },
  { id: 'etoro', name: 'eToro', color: '#13C636', mark: 'eT', rank: 191, domain: 'etoro.com', keywords: [] },
  { id: 'degiro', name: 'DEGIRO', color: '#009FE3', mark: 'Dg', rank: 192, domain: 'degiro.com', keywords: [] },
]
